export interface FontTableInfo {
  tag: string;
  length: number;
  offset: number;
}

export interface FontInfo {
  tables: FontTableInfo[];
  num_tables: number;
}

export const TABLE_DESCRIPTIONS: Record<string, string> = {
  avar: "Axis Variations Table",
  BASE: "Baseline Table",
  CBDT: "Color Bitmap Data Table",
  CBLC: "Color Bitmap Location Table",
  CFF: "Compact Font Format (Version 1)",
  CFF2: "Compact Font Format (CFF) Version 2",
  cmap: "Character to Glyph Index Mapping Table",
  COLR: "Color Table",
  CPAL: "Palette Table",
  cvar: "CVT Variations Table",
  cvt: "Control Value Table",
  DSIG: "Digital Signature Table",
  EBDT: "Extended Bitmap Data Table",
  EBLC: "Extended Bitmap Location Table",
  EBSC: "Embedded Bitmap Scaling Table",
  fpgm: "Font Program",
  fvar: "Font Variations Table",
  gasp: "Grid-fitting and Scan-conversion Procedure",
  GDEF: "Glyph Definition Table",
  glyf: "Glyph Data",
  GPOS: "Glyph Positioning Table",
  GSUB: "Glyph Substitution Table",
  gvar: "Glyph Variations Table",
  hdmx: "Horizontal Device Metrics",
  head: "Font Header Table",
  hhea: "Horizontal Header Table",
  hmtx: "Horizontal Metrics Table",
  HVAR: "Horizontal Metrics Variations Table",
  JSTF: "Justification Table",
  kern: "Kerning",
  loca: "Index to Location",
  LTSH: "Linear Threshold",
  MATH: "The Mathematical Typesetting Table",
  maxp: "Maximum Profile",
  MERG: "Merge Table",
  meta: "Metadata Table",
  MVAR: "Metrics Variations Table",
  name: "Naming Table",
  "OS/2": "OS/2 and Windows Metrics Table",
  PCLT: "PCL 5 Table",
  post: "PostScript Table",
  prep: "Control Value Program",
  sbix: "Standard Bitmap Graphics Table",
  STAT: "Style Attributes Table",
  SVG: "The SVG (Scalable Vector Graphics) Table",
  VDMX: "Vertical Device Metrics",
  vhea: "Vertical Header Table",
  vmtx: "Vertical Metrics Table",
  VORG: "Vertical Origin Table",
  VVAR: "Vertical Metrics Variations Table",
  TSI0: "Glyph Program Text Indices",
  TSI1: "Glyph Program Text UTF-8 Text Dump",
  TSI2: "VTT Talk Text Indices",
  TSI3: "VTT Talk UTF-8 Text Dump",
  TSI5: "VTT Character Group Flag",
  TSIC: "VTT Variation CVT window source",
};

export const TABLE_SPEC_LINKS: Record<string, string> = {
  "Table Directory":
    "https://learn.microsoft.com/en-us/typography/opentype/spec/otff#table-directory",
  avar: "https://learn.microsoft.com/en-us/typography/opentype/spec/avar",
  BASE: "https://learn.microsoft.com/en-us/typography/opentype/spec/base",
  CBDT: "https://learn.microsoft.com/en-us/typography/opentype/spec/cbdt",
  CBLC: "https://learn.microsoft.com/en-us/typography/opentype/spec/cblc",
  CFF: "https://learn.microsoft.com/en-us/typography/opentype/spec/cff",
  CFF2: "https://learn.microsoft.com/en-us/typography/opentype/spec/cff2",
  cmap: "https://learn.microsoft.com/en-us/typography/opentype/spec/cmap",
  COLR: "https://learn.microsoft.com/en-us/typography/opentype/spec/colr",
  CPAL: "https://learn.microsoft.com/en-us/typography/opentype/spec/cpal",
  cvar: "https://learn.microsoft.com/en-us/typography/opentype/spec/cvar",
  cvt: "https://learn.microsoft.com/en-us/typography/opentype/spec/cvt",
  DSIG: "https://learn.microsoft.com/en-us/typography/opentype/spec/dsig",
  EBDT: "https://learn.microsoft.com/en-us/typography/opentype/spec/ebdt",
  EBLC: "https://learn.microsoft.com/en-us/typography/opentype/spec/eblc",
  EBSC: "https://learn.microsoft.com/en-us/typography/opentype/spec/ebsc",
  fpgm: "https://learn.microsoft.com/en-us/typography/opentype/spec/fpgm",
  fvar: "https://learn.microsoft.com/en-us/typography/opentype/spec/fvar",
  gasp: "https://learn.microsoft.com/en-us/typography/opentype/spec/gasp",
  GDEF: "https://learn.microsoft.com/en-us/typography/opentype/spec/gdef",
  glyf: "https://learn.microsoft.com/en-us/typography/opentype/spec/glyf",
  GPOS: "https://learn.microsoft.com/en-us/typography/opentype/spec/gpos",
  GSUB: "https://learn.microsoft.com/en-us/typography/opentype/spec/gsub",
  gvar: "https://learn.microsoft.com/en-us/typography/opentype/spec/gvar",
  hdmx: "https://learn.microsoft.com/en-us/typography/opentype/spec/hdmx",
  head: "https://learn.microsoft.com/en-us/typography/opentype/spec/head",
  hhea: "https://learn.microsoft.com/en-us/typography/opentype/spec/hhea",
  hmtx: "https://learn.microsoft.com/en-us/typography/opentype/spec/hmtx",
  HVAR: "https://learn.microsoft.com/en-us/typography/opentype/spec/hvar",
  JSTF: "https://learn.microsoft.com/en-us/typography/opentype/spec/jstf",
  kern: "https://learn.microsoft.com/en-us/typography/opentype/spec/kern",
  loca: "https://learn.microsoft.com/en-us/typography/opentype/spec/loca",
  LTSH: "https://learn.microsoft.com/en-us/typography/opentype/spec/ltsh",
  MATH: "https://learn.microsoft.com/en-us/typography/opentype/spec/math",
  maxp: "https://learn.microsoft.com/en-us/typography/opentype/spec/maxp",
  MERG: "https://learn.microsoft.com/en-us/typography/opentype/spec/merg",
  meta: "https://learn.microsoft.com/en-us/typography/opentype/spec/meta",
  MVAR: "https://learn.microsoft.com/en-us/typography/opentype/spec/mvar",
  name: "https://learn.microsoft.com/en-us/typography/opentype/spec/name",
  "OS/2": "https://learn.microsoft.com/en-us/typography/opentype/spec/os2",
  PCLT: "https://learn.microsoft.com/en-us/typography/opentype/spec/pclt",
  post: "https://learn.microsoft.com/en-us/typography/opentype/spec/post",
  prep: "https://learn.microsoft.com/en-us/typography/opentype/spec/prep",
  sbix: "https://learn.microsoft.com/en-us/typography/opentype/spec/sbix",
  STAT: "https://learn.microsoft.com/en-us/typography/opentype/spec/stat",
  SVG: "https://learn.microsoft.com/en-us/typography/opentype/spec/svg",
  VDMX: "https://learn.microsoft.com/en-us/typography/opentype/spec/vdmx",
  vhea: "https://learn.microsoft.com/en-us/typography/opentype/spec/vhea",
  vmtx: "https://learn.microsoft.com/en-us/typography/opentype/spec/vmtx",
  VORG: "https://learn.microsoft.com/en-us/typography/opentype/spec/vorg",
  VVAR: "https://learn.microsoft.com/en-us/typography/opentype/spec/vvar",
  TSI0: "https://learn.microsoft.com/en-us/typography/tools/vtt/tsi-tables#tsi0-glyph-program-text-indices",
  TSI1: "https://learn.microsoft.com/en-us/typography/tools/vtt/tsi-tables#tsi1-glyph-program-text-utf-8-text-dump",
  TSI2: "https://learn.microsoft.com/en-us/typography/tools/vtt/tsi-tables#tsi2-vtt-talk-text-indices",
  TSI3: "https://learn.microsoft.com/en-us/typography/tools/vtt/tsi-tables#tsi3-vtt-talk-utf-8-text-dump",
  TSI5: "https://learn.microsoft.com/en-us/typography/tools/vtt/tsi-tables#tsi5-vtt-character-group-flag",
  TSIC: "https://learn.microsoft.com/en-us/typography/tools/vtt/tsi-tables#tsic-vtt-variation-cvt-window-source",
};

export function formatBytes(bytes: number) {
  if (bytes === 0) return "0 B";
  const k = 1024;
  const sizes = ["B", "KB", "MB", "GB"];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(2))} ${sizes[i]}`;
}
